### PR TITLE
Data key not set to null before promise resolves or rejects

### PR DESCRIPTION
**Pull request by Jackleberry**
When saving/loading the data key used to be set to null, I have changed this to leave the data key as is until the promise is resolved or rejected where it will continue with the existing behaviour: 

On resolved the data key will be set with action.payload or null if it's a find.
On rejected the data key will be set to null.

This change will stop data from flashing out for a sec whilst waiting to get a result back.

I started a discussion on this here: https://github.com/feathersjs/feathers-redux/issues/31

I have run tests and everything is fine. There are a few lint fixes that I've included in this PR.

### CODE REVIEW

**Comment by eddyystop** [comment]
I think https://github.com/Jackleberry/feathers-redux/blob/6a10bd907ad8fde3e953fe00e195bd4e43238ffe/src/index.js#L105 can be removed because of https://github.com/Jackleberry/feathers-redux/blob/6a10bd907ad8fde3e953fe00e195bd4e43238ffe/src/index.js#L100

**Comment by Jackleberry** [comment]
In that case I could remove https://github.com/Jackleberry/feathers-redux/blob/6a10bd907ad8fde3e953fe00e195bd4e43238ffe/src/index.js#L106 as well?

**Comment by Jackleberry** [comment]
Actually we can't do that because initially the state is empty.

**Comment by eddyystop** [comment]
Thanks!

**Comment by Jackleberry** [comment]
How often are new releases created? It would be nice to make a new one soonish since we're replying on this fix.

**Comment by eddyystop** [comment]
There is no schedule for the individual repos comprising Feathers. A Feathers "release" is a point in time when all the individual repos have progressively implemented the release goals. This may look awkward but it prevents a Feathers release from getting stuck because of one individual repo, as happened with the "Auk" release.

You PR has been published in 1.1.0. Thanks!

**Comment by Jackleberry** [comment]
Ah that's great, thanks.

**Pull request merged**
